name:Playwright Tests

on:
  push:
    branches: [ main ]
  pull-requests:
    branches: [ main ]

jobs:
    tests:

    runs-on: ubuntu-latest

steps:
  -name:checkout the repo code
  -uses: actions/checkout@v4
  -uses: actions/setup-node@v4
   with:
        node-version: lts/*

  -name: install dependencies
  run : npm install

  -name: install Playwright
  run:npx playwright install --with -dependencies

  -name:run playwright tests
  run:npx playwright test
